### ISSUE TITLE
enable_insights=True failed to work on UNIX when start method is not fork

### ISSUE THREAD

**Issue by tle4336** [sybrenjansen/mpire#104]
Hi Mr. Jansen @sybrenjansen , I'm currently having serious issue with the `enable_insights=True` parameter when using it in the initialization of the `pool` object as `mpire.WorkerPool(n_jobs=25, daemon=False, start_method='forkserver')`, and then within the `with mpire.WorkerPool() as pool:`, I followed the documentation of mpire with `insights = pool.get_insights()` and `print(insights)`. The error message is really weird: one time I got `cannot pickle 'weakref.ReferenceType' object`, but most of the time, the whole Python code just quits very quickly (even when I put the `mpire.WorkerPool()` statement inside the `try...except` clause to catch the potential Exception, nothing was caught).

Could you please help investigate this bug? The system I ran the code for `enable_insights=True` is UNIX on Jenkins, and I'm surprised to see how misleading the documentation is if this is a bug.

**Comment by tle4336** [comment]
Anyone can help out with this issue please? @sybrenjansen @nedbat @jonashaag @synapticarbors

**Comment by jonashaag** [comment]
Please don't ping random people on GitHub

**Comment by tle4336** [comment]
@sybrenjansen Thank you very much for your help. If I use `fork` on UNIX/LINUX system, and then use ThreadPool from `concurrent.futures` package, does it allow me to do nested WorkerPool? Because I read from the documentation of mpire (2.8.1 version) which said `forkserver` or `spawn` are the only two that works for nested WorkerPool, and I really need to use this capability.

**Comment by tle4336** [comment]
I tried your approach above, and it seems to make the code get hangover on LINUX/UNIX system (infinity buffer). Were you able to give it a test run?

**Comment by tle4336** [comment]
@sybrenjansen Thank you very much for your help, especially on letting me know that the `start_method` can be `threading` as well (this was not well documented in mpire's 2.8.1 documentation btw).

From your experience creating this great package, I wonder if you ever had a chance to **investigate** which method between `fork` and `forkserver` give a better runtime for a **nested** parallel loop where the outer loop is approximately the same/much larger than the inner loop? It looks like for a particular problem that I am having at hand, `fork` gave a better runtime than `forkserver`.

**Comment by sybrenjansen** [comment]
I haven't used nested pools that often. But generally, `fork` > `forkserver` > `spawn` when talking about the speed of creating child processes. Spawning fresh new processes is slow, hence `spawn` is slow. `fork` is fast because it simply reuses a lot of things that are already loaded in memory. `forkserver` is faster than `spawn` because you only spawn one new process and then fork from there (so it's a hybrid). 

However, `fork` also can have its downsides when doing stuff with locks and threading. I.e., it's safer to use `forkserver` or `spawn`, but if you don't do any of that tricky stuff then `fork` is usually faster and more convenient.

**Comment by tle4336** [comment]
@sybrenjansen Thank you. Your answer seems to be very much well-aligned to the one on StackOverflow (https://stackoverflow.com/questions/64095876/multiprocessing-fork-vs-spawn), and since I need use muti-thread within multi-cores, I think my best option is `forkserver` then?

**Comment by tle4336** [comment]
@sybrenjansen Also, I noticed something interesting when tracking the Console Output on Jenkins: the message seems to be printed out at around 1- 1.5 hour interval. Does it mean the workers are waiting for each other to complete the task at hand, _before_ they start communicating with each other and printing out stuffs? I was thinking that they would not wait for each other and just do the task assigned to them independently?

Also, if I need to have some tuples of `shared_objects` that would be modified by one parent process and reused by another parent worker, could I just simply turned on `shared_objects = ([args_1, args_2])` in the `with WorkerPool` clause? Does the order of `shared_objects` parameter relative to the other parameter in WorkerPool() function matter?

**Comment by tle4336** [comment]
@sybrenjansen I am so sorry for having another question, but does the `forkserver` method in `mpire` actually allows workers to access the same **local** files that are saved on the disk? If not, can you elaborate on what it can actually copy?

**Comment by sybrenjansen** [comment]
> since I need use muti-thread within multi-cores, I think my best option is forkserver then?

Using fork is only unsafe when using threading/locks before starting the child processes with fork. So if you don't have a thread running in your main process that holds a lock, you should be fine to use fork the main process and create child processes with it. Using threading after fork should be fine.

> Also, I noticed something interesting when tracking the Console Output on Jenkins: the message seems to be printed out at around 1- 1.5 hour interval. Does it mean the workers are waiting for each other to complete the task at hand, before they start communicating with each other and printing out stuffs? I was thinking that they would not wait for each other and just do the task assigned to them independently?

MPIRE first creates all workers and starts them (i.e. calls `process.start()`). But it doesn't wait for the workers to be started. One worker can already start a task while another is still starting.  It could be that your console output uses a buffer for `stdout` and outputs every x time, giving the impression that mpire waits/syncs. 

See the following output:
```
from mpire import WorkerPool

def w_init(worker_id):
    print(worker_id, "started")

def job(worker_id, x):
    print(worker_id, "got task", x)
    return x * 2

with WorkerPool(10, pass_worker_id=True) as pool:
    pool.map(job, range(10), worker_init=w_init)
```
On my machine this prints:
```
0 started
1 started
2 started
3 started
0 got task 0
1 got task 1
4 started
5 started
2 got task 2
6 started
3 got task 3
4 got task 4
5 got task 5
7 started
6 got task 6
8 started
9 started
7 got task 7
8 got task 8
9 got task 9
```

> Also, if I need to have some tuples of shared_objects that would be modified by one parent process and reused by another parent worker, could I just simply turned on shared_objects = ([args_1, args_2]) in the with WorkerPool clause? Does the order of shared_objects parameter relative to the other parameter in WorkerPool() function matter?

The order of shared objects doesn't matter, each worker will get the same shared objects. However, modifying shared objects might not work like you think it would. They are not mutable in a multiprocessing context. When one process makes modifications, it does so on a copy. 

E.g., see the following example:

```
def job(worker_id, shared_objects, x):
     # At this point shared_objects is the same for each child process
     args_1, args_2 = shared_objects
     print(worker_id, args_1)
 
     # Other processes won't notice any changes in args
     if worker_id == 0:
         args_1.append(3)
 
if __name__ == "__main__":
    args_1, args_2 = [1], [2]
    with WorkerPool(4, pass_worker_id=True, shared_objects=[args_1, args_2]) as pool:
        pool.map(job, range(10))
```
This will output:
```
0 [1]
1 [1]
2 [1]
0 [1, 3]
3 [1]
1 [1]
2 [1]
0 [1, 3, 3]
3 [1]
1 [1]
```
As you can see, only the shared objects for one worker are updated (worker `0` in this case). 

When using threading as start method, this will work, however. The output, with the same code (but changing start method) is then:
```
0 [1]
1 [1, 3]
3 [1, 3]
0 [1, 3]
2 [1, 3, 3]
1 [1, 3, 3]
3 [1, 3, 3]
0 [1, 3, 3]
2 [1, 3, 3, 3]
1 [1, 3, 3, 3]
```

If a process should see the changes another one is making (and you're not using threading), you need to make use of some process communication primitive. Depending on your data type, either using `multiprocessing.Value`, `multiprocessing.Array` or `multiprocessing.Manager`.

> does the forkserver method in mpire actually allows workers to access (i.e, read & write) the same local files that are saved on the disk? If not, can you elaborate on what it can actually copy?

Child processes are created on the same machine, so they can access the same disks/files no problem. The difference with fork/forkserver/spawn is with the memory (RAM). Fork processes can access stuff that is already loaded in RAM by the main process at the point the forking happened. Forkserver/spawn processes can not and you have to reload stuff in memory. 

Example:
```
DATA = None

def job(x):
    print(DATA)

if __name__ == "__main__":
    DATA = "some string"
    with WorkerPool(4, start_method="forkserver") as pool:
        pool.map(job, range(5))
```
This will output:
```
None
None
None
None
None
```
For spawn the output will be the same. However, for fork, you get:
```
some string
some string
some string
some string
some string
```
This is because forked processes reuse memory. For forkserver and spawn get a fresh start.

Hope this helps.

**Comment by tle4336** [comment]
@sybrenjansen Thank you very much for your wonderfully detailed answers to my questions, Mr. Jansen. They are super helpful to me. 

Regarding your first answer, I have a follow-up question: if I use `multiprocessing.lock()` within the parent process to avoid 'race condition' that occurs when reading and decompressing `.gz` files (I also used `fcntl.flock(fr, fcntl.LOCK_EX | fcntl.LOCK_NB)` within every `with pgzip.open()` but before calling the `read()` function), but this step occurs  _before_ threading, is it still safe to use `fork` for the parent process? I noticed that `fork` is significantly faster for my program to begin with, so I really prefer using it as a default choice IF the `threading` works as it is supposed to do so.

**Comment by sybrenjansen** [comment]
No problem, happy to help.

To answer your question, as long as you are sure all locks are released before starting forking processes, it shouldn't be a problem. 

The problems start when you have a thread in your main process that holds a lock and then start forking. A child process then inherits an acquired lock which cannot be released anymore because the thread that holds it is not inherited. So whenever you do something with that lock again it will deadlock because it cannot acquire an already acquired lock.

**Comment by tle4336** [comment]
@sybrenjansen Hi Mr. Jansen, thank you very much for your great help. I think I almost got it working in terms of the outer-loop being run with multi-cores and then some sub-functions inside being run with multi-threading, all using `mpire` package!! However, I accidentally bumped into this error that I would appreciate your insight as I wonder whether this came from "maxing out the number of threads" (I don't think this is the case, as I only used 4 cores and call 16 threads within each core, which is far below the 96 threads of 48 cores in the Docker container), or it came from something else that I really had no idea how to circumvent:

Child worker 0 starts!
Child worker 7 starts!
Child worker 4 starts!
Child worker 13 starts!
Child worker 8 starts!
Child worker 2 starts!
Child worker 3 starts!
Child worker 9 starts!
Child worker 14 starts!
Child worker 1 starts!
Child worker 11 starts!
Child worker 5 starts!
Child worker 6 starts!
Child worker 12 starts!
Child worker 10 starts!
Child worker 15 starts!
Child None fails Traceback (most recent call last):
`File "/****-python/app/[opt.py", line 1324, in ent_opt
            for ctr in pool.map(constr, args):
File "/****-python/.local/lib/python3.10/site-packages/mpire/pool.py", line 462, in map
          results = self.map_unordered(
File "/****-python/.local/lib/python3.10/site-packages/mpire/pool.py", line 534, in map_unordered
        return list(self.imap_unordered(func, iterable_of_args, iterable_len, max_tasks_active, chunk_size,
File "/****-python/.local/lib/python3.10/site-packages/mpire/pool.py", line 791, in imap_unordered
        yield imap_iterator.next(block=True, timeout=0.1)
File "/****-python/.local/lib/python3.10/site-packages/mpire/async_result.py", line 161, in next
       timed_out = not self._condition.wait(timeout=timeout)
File "/usr/local/lib/python3.10/threading.py", line 324, in wait
       gotit = waiter.acquire(True, timeout)
File "/****-python/.local/lib/python3.10/site-packages/mpire/worker.py", line 250, in _on_exception_exit_gracefully
      raise StopWorker
mpire.exception.StopWorker`

**Comment by sybrenjansen** [comment]
The timeout is in seconds, yes. However, you should never see a  `StopWorker` exception in your terminal, as that is used internally only. 

You can email me at [github-username]@gmail.com

**Comment by tle4336** [comment]
@sybrenjansen So I tested it out locally, and I think I found the reason why that error came out. Sorry it still took me a while before I can send you the **minimal** working example. In the meantime, because the data manipulation step for calling `threading` inside each parent process involves `pulp` to build up the constraints for a LP problem, could you please help check if what `pchtsp` shares in the following post also applies to `mpire`? https://github.com/coin-or/pulp/discussions/357

**Comment by sybrenjansen** [comment]
If pulp has trouble with regular multiprocessing, it will likely have the same issues with mpire as mpire is using parts of Python's multiprocessing library under the hood

**Comment by tle4336** [comment]
@sybrenjansen That is a pretty bad news for me to learn from. But I appreciate to have a confirmation from you - the author. Thank you very much for your help. Do you think that kind of conflict is what caused the Exception Error I posted earlier? Because the `threading` step was called out only in the process of building thousands of constraints being added to the `pulp` object. 

I will send you the **minimal** working example, although even that example is pretty large as well.

**Comment by sybrenjansen** [comment]
No, the exception you saw shouldn't happen. So I'm still curious to see the example and try it for myself to see what's going on

**Comment by tle4336** [comment]
@sybrenjansen I have a quick question: if I want to have a shared_object among all the processes, can I do that by specifying those objects via `multiprocessing.Manager().list()/dict()`, or do I have to turn on the `shared_objects=([list of parameters])` in `mpire.WorkerPool()`?

**Comment by tle4336** [comment]
@sybrenjansen I hope you had a great Thanksgiving. I would like to follow up with you regarding the `mpire.Exception.StopWorker`. When I tried printing out the `Worker_ID` to see which worker caused that error I got a very strange number, as I only used 6 threads per each parent process (and I have 10 of them):

```
19:47:14 Child worker 2 starts!
19:47:14 Child worker 0 starts!
19:47:14 Child worker 1 starts!
19:47:14 Child worker 4 starts!
19:47:14 Child worker 5 starts!
19:47:14 Child worker 3 starts!
19:49:40 Child 9 fails Traceback (most recent call last):
19:49:40   File "/****-python/app/optimization.py", line 1324, in parallel_overlap
19:49:40     for ctr in pool.map(constr, args):
19:49:40   File "/****-python/.local/lib/python3.10/site-packages/mpire/pool.py", line 462, in map
19:49:40     results = self.map_unordered(
19:49:40   File "/****-python/.local/lib/python3.10/site-packages/mpire/pool.py", line 534, in map_unordered
19:49:40     return list(self.imap_unordered(func, iterable_of_args, iterable_len, max_tasks_active, chunk_size,
19:49:40   File "/****-python/.local/lib/python3.10/site-packages/mpire/pool.py", line 791, in imap_unordered
19:49:40     yield imap_iterator.next(block=True, timeout=0.1)
19:49:40   File "/****-python/.local/lib/python3.10/site-packages/mpire/async_result.py", line 161, in next
19:49:40     timed_out = not self._condition.wait(timeout=timeout)
19:49:40   File "/usr/local/lib/python3.10/threading.py", line 324, in wait
19:49:40     gotit = waiter.acquire(True, timeout)
19:49:40   File "/****-python/.local/lib/python3.10/site-packages/mpire/worker.py", line 250, in _on_exception_exit_gracefully
19:49:40     raise StopWorker
19:49:40 mpire.exception.StopWorker 
```

Is there a way to adjust the parameter `timeout=0.1`

**Comment by sybrenjansen** [comment]
> I know this is impossible based on the mpire's documentation, but Is it possible at this point to use fork in both parent and child processes? Or threading on the parent process and then fork on the child process?

Using fork with fork should be absolutely fine. The documentation doesn't advice against it, does it? 
And you cannot use threading on the parent process and then fork. Believe me, I tested it. Creating processes is not thread-safe and it will break everything :) 

> Also, if I potentially encounter maximum recursion depth exceeded, would that invoke the ExceptionError above?

It shouldn't as far as I'm aware.

> if I want to have a shared_object among all the processes, can I do that by specifying those objects via multiprocessing.Manager().list()/dict(), or do I have to turn on the shared_objects=([list of parameters]) in mpire.WorkerPool()?

You can use a manager, no problem. That is usually the way to go when you need your processes to write results to the same object. However, managers are really slow. Data needs to be serialized and send to a server process, which unserializes it and sequentially adds the data. So there's also a lot of locking required. Even if you only read from it. If you don't need writing, I would advice using a normal list/dict and passing it on the processes using mpire's `shared_objects`

> When I tried printing out the Worker_ID to see which worker caused that error I got a very strange number, as I only used 6 threads per each parent process (and I have 10 of them):

So, to get this straight. You have your main process in which you created 10 workers (using fork), and each worker creates 6 threads. If you get `Child 9 fails` then that should mean the exception is happening within one of the fork-workers. Well, actually the error is triggered from one of the threads, and passed on to the parent process, which will then raise it on behalf of the child process. 

> I think there are only two possible causes: first is the parameter timeout=0.1, and second is the fact that daemon=True was the default value when applying threading for the child process (the parent process has daemon=False)? Do you think I should set daemon=False for the child process, or if I should change timeout=0.1 to something else?

The `timeout` parameter shouldn't matter. Also, `daemon` is ignored when using threading as start method. It only applies to the other start methods.

**Comment by tle4336** [comment]
@sybrenjansen Thank you so much for your great help. You are right that with nested WorkerPool, we can use `fork` and `fork` when doing it with `mpire`. I think I tried it before but it seems slower/more error-prone than using `fork` and `threading`. I might perhaps try it out again. Do you recommend setting both `daemon=False` with `fork` and `fork`?

#So, to get this straight. You have your main process in which you created 10 workers (using fork), and each worker creates 6 threads. If you get Child 9 fails then that should mean the exception is happening within one of the fork-workers.

This makes great sense to me!! Thank you so much for your help in uncovering this. Is there a way to know which worker belongs to a parent process, and which worker belongs to the child process, mainly for _debugging_ purposes, given that they might have the same `Worker_ID` (but probably different hashcodes or something underneath)?

**Comment by tle4336** [comment]
> > I know this is impossible based on the mpire's documentation, but Is it possible at this point to use fork in both parent and child processes? Or threading on the parent process and then fork on the child process?
> 
> Using fork with fork should be absolutely fine. The documentation doesn't advice against it, does it? And you cannot use threading on the parent process and then fork. Believe me, I tested it. Creating processes is not thread-safe and it will break everything :)
> 
> > Also, if I potentially encounter maximum recursion depth exceeded, would that invoke the ExceptionError above?
> 
> It shouldn't as far as I'm aware.
> 
> > if I want to have a shared_object among all the processes, can I do that by specifying those objects via multiprocessing.Manager().list()/dict(), or do I have to turn on the shared_objects=([list of parameters]) in mpire.WorkerPool()?
> 
> You can use a manager, no problem. That is usually the way to go when you need your processes to write results to the same object. However, managers are really slow. Data needs to be serialized and send to a server process, which unserializes it and sequentially adds the data. So there's also a lot of locking required. Even if you only read from it. If you don't need writing, I would advice using a normal list/dict and passing it on the processes using mpire's `shared_objects`
> 
> > When I tried printing out the Worker_ID to see which worker caused that error I got a very strange number, as I only used 6 threads per each parent process (and I have 10 of them):
> 
> So, to get this straight. You have your main process in which you created 10 workers (using fork), and each worker creates 6 threads. If you get `Child 9 fails` then that should mean the exception is happening within one of the fork-workers.
> 
> When an error is triggered from one of the threads, it is passed on to the parent process, which will then raise it on behalf of the child process. But the `StopWorker` one is happening in the forked process.
> 
> > I think there are only two possible causes: first is the parameter timeout=0.1, and second is the fact that daemon=True was the default value when applying threading for the child process (the parent process has daemon=False)? Do you think I should set daemon=False for the child process, or if I should change timeout=0.1 to something else?
> 
> The `timeout` parameter shouldn't matter. Also, `daemon` is ignored when using threading as start method. It only applies to the other start methods.

**Comment by tle4336** [comment]
@sybrenjansen Do you know what could cause the `StopWorker` to be invoked? I remember you mentioned that I should not see it regardless.

**Comment by tle4336** [comment]
>You can use a manager, no problem. That is usually the way to go when you need your processes to write results to the same object. However, managers are really slow. Data needs to be serialized and send to a server process, which unserializes it and sequentially adds the data. So there's also a lot of locking required. Even if you only read from it. If you don't need writing, I would advice using a normal list/dict and passing it on the processes using mpire's shared_objects

Is it possible that you can add a functionality for `mpire` to have the shared_objects of `list/dict/tuple` being written over time by multiple processes?

**Comment by sybrenjansen** [comment]
> Do you recommend setting both daemon=False with fork and fork?

I haven't experimented with that. Daemon does the following (taken from the multiprocessing docs): 

```
When a process exits, it attempts to terminate all of its daemonic child processes.

Note that a daemonic process is not allowed to create child processes. Otherwise a daemonic process would leave its children orphaned if it gets terminated when its parent process exits.
```

So choose based on what you need.

> Is there a way to know which worker belongs to a parent process, and which worker belongs to the child process, mainly for debugging purposes, given that they might have the same Worker_ID

You can use `os.getpid()` to get the current process ID. You can also get the parent process ID by using `os.getppid()`. This should give you unique identifiers for each worker.

> I got a workaround solution for mpire.Exception.StopWorker by using the try...except clause. 

It still shouldn't happen though. So I'm still curious to see a working example :) 

> Is it possible that you can add a functionality for mpire to have the shared_objects of list/dict/tuple being written over time by multiple processes?

If you want that you should use a manager. You can import it yourself and pass it on to the workers like so:

```
import multiprocessing as mp
from mpire import WorkerPool

def job(shared_list, x):
    shared_list.append(x)

def main():
    shared_list = mp.Manager().list()
    with WorkerPool(4, shared_objects=shared_list) as pool:
        pool.map(job, range(10))
    print(shared_list)
```
This outputs `[0, 1, 4, 2, 3, 5, 8, 6, 7, 9]` on my machine. But the order will be different each run.

I cannot convert every list/dict someone passes on as shared objects to a manager object as I can't infer if the user wants it to be writable or not. As managers are slow, I will also not simply assume it is so.

**Comment by tle4336** [comment]
@sybrenjansen Hi Mr. Jansen, I hope you are doing well. I'm sorry for having to bother you again, but I'm currently in need of testing the **modifiable** `shared_objects=(x, y, z)` where each `x,y,z` are created from `multiprocessing.Manager().dict()`. Also, I have a function `opt_month(worker_id: object, x,y,z, t)` that I would put into `pool.map()`. So the entire code structure would be:

```
def opt_month(worker_id, shared_objects, code_remove, t):
     x,y,z = shared_objects[0], shared_objects[1], shared_objects[2]
     [steps that would modify keys of the x,y,z since they are dict-type objects]
     return [object_name]

shared_objects = (x,y,z)
 with mpire.WorkerPool(n_jobs=48, shared_objects=shared_objects, pass_worker_id=True, start_method='fork', daemon=False) as pool:
        args = [(code_remove, t) for t in range(len(100))]
        pool.map(opt_month, args)
```

My question is: how do I know if `x,y,z` are actually shared among workers? By that I meant, I don't want the same keys to be computed twice within each of `x,y,z` (for example, if `worker 1` handles `x[1], x[2]` , `worker 2` can retrieve the values of `x[1], x[2]` rather than re-computes it).

**Comment by sybrenjansen** [comment]
Have a look at https://stackoverflow.com/questions/8640367/manager-dict-in-multiprocessing.

What I suspect is that you're updating the dict values like so:
```
x[idx].append(some_value)
```
This doesn't trigger a data update on the Manager's side, because you're updating a mutable object inside the dict and the Manager has no way of knowing you updated that object (list in this case). What you need to do instead is:
```
x[idx] = x[idx] + [some_value]
```
This will trigger a change because `__setitem__` will now be called on the dict object and you will get output similar to:
```
In [19]: def opt_month(worker_id, shared_dict, t):
    ...:     print(worker_id, t)
    ...:     shared_dict[0] = shared_dict[0] + [t]
    ...: 

In [20]: x = m.dict()

In [21]: x[0] = []

In [22]: with WorkerPool(n_jobs=4, shared_objects=x, pass_worker_id=True, start_method='fork', daemon=False) as pool:
    ...:     pool.map(opt_month, range(10))
    ...: 
0 0
1 1
2 2
0 4
0 8
2 6
1 5
2 9
3 3
3 7

In [23]: x[0]
Out[23]: [0, 4, 1, 6, 5, 9, 3, 7]
```
However, notice that we're missing some values here. This is because we now introduced a racing condition. If multiple workers are reading/writing to the same idx at the same time, this can happen. You can circumvent that with a lock
```
In [33]: def opt_month(worker_id, shared_objects, t):
    ...:     shared_dict, shared_lock = shared_objects
    ...:     with shared_lock:
    ...:         shared_dict[0] = shared_dict[0] + [t]
    ...: 

In [33]: l = m.Lock()

In [35]: x[0] = []

In [36]: with WorkerPool(n_jobs=4, shared_objects=(x, l), pass_worker_id=True, start_method='fork', daemon=False) as pool:
    ...:     pool.map(opt_month, range(10))
    ...: 

In [37]: x[0]
Out[37]: [0, 1, 2, 4, 5, 8, 6, 9, 3, 7]
```
Now it works, yay! But the downside of this approach is that this is now slower than without multiprocessing because of the locking. 

This issue of assigning/locking only happens when you're updating mutable dictionary values. You can remove the locking if you can guarantee two workers won't read/write to the same key at the same time. Or, if that's not possible, create as many locks as keys in your dictionary and only use the lock for the specific key. Then you should only have a small overhead of acquiring a lock, but multiple workers should still be able to update different keys at the same time.

**Comment by tle4336** [comment]
@sybrenjansen Thank you very much for your great help into this problem (as usual). The way I updated `x[0]` was, for example, `x[0] = 1`. And then with the usage of an `IF` clause, some other workers would just pick up `x[0]=1` rather than having to re-compute it themselves. This certainly leads to the race condition as you mentioned (hence we need to use `locking` as you pointed out, but I didn't know it's even slower than **without multiprocessing**). Based on my observation,, `x[0]=1` is still getting re-computed within each worker. I assume it's because **all** the workers are kicked off _in parallel_ at the same time? If this is true, Is there a way to kick off workers **with some lag times (for example, worker 2 gets started 5 seconds later than worker 1, worker 3 gets started 5 seconds later than worker 2, and so on)?

**Comment by sybrenjansen** [comment]
Well, if you put in locks such that no worker can process stuff at the same time, but they have to wait for each other, then it's nothing better than sequential.

To introduce lag times, you can make use of the `worker_init` function and put a `time.sleep` in there based on the worker ID. E.g.:

```
def init(worker_id):
    time.sleep(worker_id)

def task(worker_id, ...):
    pass

with WorkerPool(n_jobs=4, pass_worker_id=True) as pool:
    pool.map(task, range(100), worker_init=init)
```
