### ISSUE TITLE
start_dashboard hangs if there aren't two available ports in the provided range

### ISSUE THREAD

**Issue by harmenwassenaar** [sybrenjansen/mpire#112]
The main process simply keeps waiting for DASHBOARD_STARTED_EVENT to be set, which never happens when the "all ports used" exception occurs in the child process.

**Comment by sybrenjansen** [comment]
Ah yes, I see. Seems you can easily fix it by altering the `start_dashboard` function to something like this:
```
while not DASHBOARD_STARTED_EVENT.wait(timeout=0.01):
    if process.join(timeout=0.01):
        raise ....
```
If the process joins, then apparantly an exception occurred.

Perhaps storing the exception of the `_run` function and raising that is better, but it requires more work.
