### ISSUE TITLE
Unexpected worker deaths

### ISSUE THREAD

**Issue by umarbutler** [sybrenjansen/mpire#130]
I've been using `mpire` for a number of years now and, although I have found it exceptionally useful, something that has always bothered me is when workers unexpectedly die. This has happened for years and every time I am unable to identify the root cause. Whether it is chunking documents, scraping websites, OCRing PDFs or anything else, sometimes scripts will just fail and it can be quite frustrating. I either have to rerun my scripts a couple times hoping that they work without any interruptions or, if they fail enough times, I need to refactor them to be able to resume progress by saving data as it is processed and also handling corruption that might occur as a result of interruption during saving.

When I swap `mpire` out for single processing, it will work perfectly. I noticed @sybrenjansen that you mentioned in [this](https://github.com/sybrenjansen/mpire/issues/110#issuecomment-1874415416) comment that 'Unexpected deaths usually means that the OS/kernel killed your process. One cause that jumps to mind is due to running out of memory'. That seems to have been the case this latest instance. I was using different 30 processes to OCR documents and didn't realise that by converting all of their pages to images before passing them to Tesseract, I was exceeding my memory (since some documents could have up to 600 pages).

Normally, when you go OOM in Python, there is a specific error that will be raised. Yet, I am certain that over the years, whenever I have encountered this error, I almost never see a `MemoryError` raised.

Is there some way to ensure that `MemoryError`s are raised where that is the cause of a worker's death. Alternatively, could the error message be updated to list some of the most common known causes of unexpected worker deaths. I'm assuming @sybrenjansen that you have built a mental list from your own personal experience over the years. At least noting that memory could be the cause would be extremely useful.

By reducing the memory usage of my script, I have not had an interruption since. Having that idea raised in the error message would've helped me reach this solution earlier.

**Comment by sybrenjansen** [comment]
Thnx for submitting this issue.

You're usually not able to catch memory errors, specifically in a multiprocessing context. According to the docs, memory errors can only be caught when the situation can still be recovered by deleting some other objects. But in a MP context many processes are fighting for resources, so in the fast majority of cases, these situations can't be recovered. 

Even trying something like:
```
try:
    np.random.rand(int(1e10))
except MemoryError:
    print("mem error caught")
```
doesn't work. The OS simply kills the process and that's that.

But your suggestion of adding more information to the error message is a good one. I will definitely do that
