### ISSUE TITLE
resource_tracker: There appear to be 32 leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by sailxjx** [sybrenjansen/mpire#27]
I've got this message by resource tracker when I use `spawn` mode on my mac, the code is really simple:

```
import time
from mpire import WorkerPool


def global_runner(*args):
    print("I am Running", args)
    time.sleep(0.3)
    return


if __name__ == "__main__":
    params_group = [1, 2]
    with WorkerPool(n_jobs=2, start_method="spawn") as pool:
        pool.map(global_runner, params_group)
```

<img width="1626" alt="Screen Shot 2021-12-01 at 17 19 32" src="https://user-images.githubusercontent.com/909853/144207118-ff2a9090-142e-4863-b195-0076ece6584d.png">

Can anyone help me solve this problem?

**Comment by sailxjx** [comment]
The version of python is 3.9.7

**Comment by sybrenjansen** [comment]
Hmm.. Unfortunately I don't have a mac to be able to debug this. When testing this on linux using python 3.9.7 your script works just fine and doesn't give the warnings. So it's probably mac specific.

However, it is only a warning at the end of the script, and a warning like this can be safely ignored. I.e., your code should still work fine.

If someone else wants to do some debugging, please do so. The only semaphores being used in mpire are within JoinableQueues in `mpire/comms.py`.

**Comment by macintacos** [comment]
Don't ask me how, but I seem to be consistently getting this when using a WorkerPool with `progress_bar=True`. When I remove the progress bar (and remove `start_method="spawn"`) the issue goes away.

**Comment by jonashaag** [comment]
There is definitely a bug here that leaks semaphores. It causes macOS to run out of file descriptors.

**Comment by sybrenjansen** [comment]
Bug has been found. Mac support will be added soon
