### ISSUE TITLE
Set cpu_ids doesn't work on intel macbook

### ISSUE THREAD

**Issue by ibnubay** [sybrenjansen/mpire#79]
mpire version: v2.7.1
python version: 3.10.11

Code:
`with WorkerPool(n_jobs=2, cpu_ids=[2, 3]) as pool:`

Error messages:
`AttributeError: module 'os' has no attribute 'sched_setaffinity'`

Is option `cpu_ids` only work on linux?

Ty

**Comment by sybrenjansen** [comment]
I have tested mpire only on linux and windows, so there could be some stuff not working on mac as you experienced.

Unfortunately, from a quick browse on the internet it seems that Mac doesn't support setting the affinity. However, I haven't done a thorough search so if someone knows how to accomplish this, then feel free to submit a PR.

**Comment by sybrenjansen** [comment]
Indeed, macOS doesn't support this. I will change the code to raise an appropriate error and document it in the next release
