### ISSUE TITLE
MPIRE does not close process/is stuck?

### ISSUE THREAD

**Issue by Keyn34** [sybrenjansen/mpire#81]
Hello All!

### Background
I would like to ask a question regarding the utilization of MPIRE for tasks that do not involve computation. 
To split a larger image (nifti, medical image format) into three chunks for further processing, we use [nibabel](https://nipy.org/nibabel/) for reading the image and MPIRE for writing the three image chunks in parallel. The reason is to speed up the process and make the files available quicker on disk for further processing. The speedup is noticeable. 

### System information
I am using Python 3.10.6 on an Ubuntu 22.04.2 LTS system.  

### Relevant code/implementation
Below, I've included the implementation of the two relevant functions. 
The function that handles the writing of each chunk, mapped by MPIRE:

```
def split_and_save(shared_image_data, z_index, image_chunk_path):
    image_data, image_affine = shared_image_data
    image_part = nib.Nifti1Image(image_data[:, :, z_index[0]:z_index[1]], image_affine)
    nib.save(image_part, image_chunk_path)
```

And the function that prepares the argument dictionary and the shared objects invokes the worker pool and the corresponding map function:
```
def handle_large_image(image: nib.Nifti1Image, save_dir):
    image_shape = image.shape
    image_data = image.get_fdata()
    image_affine = image.affine

    if np.prod(image_shape) > constants.MATRIX_THRESHOLD and image_shape[2] > constants.Z_AXIS_THRESHOLD:

        # Calculate indices for z-axis split
        z_part = image_shape[2] // 3
        z_indices = [(0, z_part + constants.MARGIN_PADDING),
                     (z_part + 1 - constants.MARGIN_PADDING, z_part * 2 + constants.MARGIN_PADDING),
                     (z_part * 2 + 1 - constants.MARGIN_PADDING, None)]
        filenames = ["subpart01_0000.nii.gz", "subpart02_0000.nii.gz", "subpart03_0000.nii.gz"]
        resampled_chunks_paths = [os.path.join(save_dir, filename) for filename in filenames]

        chunk_data = []
        for z_index, resampled_chunk_path in zip(z_indices, resampled_chunks_paths):
            chunk_data.append({"z_index": z_index,
                               "image_chunk_path": resampled_chunk_path})

        shared_objects = (image_data, image_affine)

        with WorkerPool(n_jobs=3, shared_objects=shared_objects) as pool:
            pool.map(split_and_save, chunk_data)

        return resampled_chunks_paths

    else:
        resampled_image_path = os.path.join(save_dir, constants.RESAMPLED_IMAGE_FILE_NAME)
        nib.save(image, resampled_image_path)

        return [resampled_image_path]
```
### The Problem
I noticed an unexpected behaviour with this procedure: While the code always works for a single image (meaning that one image is read and split into three chunks and written), the process silently stops for multiple images (when a second or third image is read, split and written after each other). When I interrupt the process, the terminal output indicates that MPIRE did not finish the process properly and is, to my understanding, stuck (?). I also tried to return from the function `split_and_save`, but this did not resolve the problem. 

Is there any way to prevent this, or am I using MPIRE wrong and not as intended? Thank you so much in advance!

For completeness, the relevant output after stopping the stuck process:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/pool.py", line 779, in _terminate_worker
    os.kill(worker_process.pid, signal.SIGUSR1)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 239, in ident
    self._check_closed()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 101, in _check_closed
    raise ValueError("process object is closed")
ValueError: process object is closed
Exception in thread Thread-18 (_terminate_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    Exception in thread self.run()Thread-19 (_terminate_worker)
:
  File "/usr/lib/python3.10/threading.py", line 953, in run
Traceback (most recent call last):
      File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self._target(*self._args, **self._kwargs)
  File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/pool.py", line 807, in _terminate_worker
    self.run()    
self._worker_comms.drain_queues_terminate_worker(worker_id, dont_wait_event)
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/comms.py", line 597, in drain_queues_terminate_worker
        self._target(*self._args, **self._kwargs)self.get_results(block=False, in_thread=True)

  File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/pool.py", line 807, in _terminate_worker
  File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/comms.py", line 313, in get_results
    self._worker_comms.drain_queues_terminate_worker(worker_id, dont_wait_event)
      File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/comms.py", line 597, in drain_queues_terminate_worker
self._last_completed_task_worker_id, results = self._results_queue.get(block=block, timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 100, in get
    self.get_results(block=False, in_thread=True)
      File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/comms.py", line 313, in get_results
raise ValueError(f"Queue {self!r} is closed")
ValueError:     Queue <multiprocessing.queues.JoinableQueue object at 0x7fc239f420b0> is closedself._last_completed_task_worker_id, results = self._results_queue.get(block=block, timeout=timeout)
```

**Comment by sybrenjansen** [comment]
The output you're seeing is the result of interrupting mpire. It doesn't show where it was stuck. I'm curious though to what version of mpire you are using? The line 
```
File "/home/horyzen/MOOSEz/lib/python3.10/site-packages/mpire/pool.py", line 779, in _terminate_worker
    os.kill(worker_process.pid, signal.SIGUSR1)
```
in the latest version is protected by a `try/except` block which should catch the `ValueError`.  The termination should be more smooth.

Anyway, that doesn't solve your actual problem of course.

So, when you say it stops working for multiple images, you're effectively calling `handle_large_image` multiple times in a row and so also create multiple `mpire.WorkerPool`s in a row, right? This should be absolutely fine, I see no problems with it.

I can think of a few possible reasons for freezing:

- Maybe there is an error with the script, but the older version you're using of mpire still has some issues with error handling and mpire itself is indeed freezing. Install a newer version and try again
- Data is corrupt and the library you're using is freezing. Have you tried running it sequentially to see if doesn't give the same issues?

**Comment by Keyn34** [comment]
Thanks @sybrenjansen, 

This is what I thought, yes. I interrupted the process because I noticed nothing was proceeding, and the operation of writing files was done long before. I can already confirm that running the code without mpire works. And funnily enough, it also works on Windows because the fork method is not available (at least this is what I think the reason might be). 

I will update mpire and see if this changes something. Thank you for the suggestion!

**Comment by sybrenjansen** [comment]
Did you manage to try it with a newer version of mpire? I'm curious to know the result

**Comment by Keyn34** [comment]
Hi @sybrenjansen, and sorry for the delay. Vacation time hit. :D We will test it this week and inform you if the update changes something!

**Comment by sybrenjansen** [comment]
No worries. Hope you had a great holiday. Let me know your results :)

**Comment by Keyn34** [comment]
@SultanOrazbayev Sorry for the further delay. We tried it with the latest MPIRE version now (2.8.0). The issue, unfortunately, persists.

**Comment by sybrenjansen** [comment]
That is unfortunate, indeed. 

I would very much like to get to the bottom of this. Is it possible for you to share a a minimum non-working example with some data with me? Then I can debug locally, which will be somewhat quicker than going back and forth.

**Comment by Keyn34** [comment]
@sybrenjansen I will see what I can do to patch up an example. :) I will let you know!

**Comment by Keyn34** [comment]
@sybrenjansen, in a minimal example, where I only read the image and chunk it according to the initial issue post, the problem does not occur. Could the next processing step (invoking a `subprocess` with [nnUNet](https://github.com/MIC-DKFZ/nnUNet)) be the issue? Are there any known potential conflicts? Or the `subprocess` package of Python itself? 

And to follow up on your request, is there a way to contact you privately to send you the image data? And the minimal script? :)

But at this stage, I don't think that mpire is at "fault" here...

**Comment by sybrenjansen** [comment]
I haven't tried using `subprocess` in combination with multiprocessing, but when searching through the github repo I only see `subprocess.getoutput(['hostname'])` calls that use `subprocess`. Testing this in a simple function with mpire doesn't give any issues.

I do, however, see things like `torch.set_num_threads(multiprocessing.cpu_count())` and numerous cases where they use a multiprocessing pool. If you have `n` cores and use mpire with `n` workers and each worker will again spawn `n` processes, then it will slow down processing considerably because each process will be fighting for resources. Additionally, in some situations the amount of threads you're able to spawn will exceed some system limit, which should throw an error. But I can also imagine that some low-level code would freeze because of this.

Either way, I would still like to verify this. You can send me an email at <my username> [at] gmail [dot] com

**Comment by sybrenjansen** [comment]
Closing this for now because the issue is stale. Feel free to reopen if the problem persists and you can send me an example script
