### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by jon-huff** [sybrenjansen/mpire#85]
I am trying to install mpire in one of my environments, but it's throwing Errno -3 Temporary failure in name resolution.  I see a new version just got released (2.8.0) today 2023-8-16. I have 2.7.1 installed in other environments so I tried specifying that version on the install, but getting same error.  Thanks.

**Comment by jon-huff** [comment]
My apologies, it looks like my server has a dns config issue.

**Comment by sybrenjansen** [comment]
No worries. I'm glad it works now :)
