### ISSUE TITLE
Doesn't seem to start enough jobs?

### ISSUE THREAD

**Issue by rachtsingh** [sybrenjansen/mpire#86]
When I start a job with:

```python
with WorkerPool(n_jobs=24, keep_alive=True) as pool:
    pool.map_unordered(do_work, arg_list, worker_lifespan=2, chunk_size=1, progress_bar=True)
```

I only seem to see 7% avg CPU usage on our m7i.8xlarge (32 vCPUs). Am I using this wrong? When I run

```python
tqdm.contribu.concurrent.process_map(do_work, arg_list, max_workers=24, chunksize=1, maxtasksperchild=2)
```

I see 75% usage, as expected (caveat: I'm using our wrapper around that function that supports maxtasksperchild, but it's basically the same). Is there a recommended way to debug this?

**Comment by sybrenjansen** [comment]
Your code seems fine to be honest. I never had issues with cpu usage, it usually is always at 100%. 

What happens with the cpu usage when you don't use `worker_lifespan`? If you experiment a bit with different settings then maybe we can pinpoint the problem.

**Comment by sybrenjansen** [comment]
Stale
