### ISSUE TITLE
shared objects and args

### ISSUE THREAD

**Issue by sroener** [sybrenjansen/mpire#87]
Hi, 

first of all, thank you for writing this package! It helped me for using multiprocessing with a lot less headache than other solutions!

Now to the main part. I have a question about using shared objects:

I have a case, where I want to do a lot of parallel computations with many "constant" arguments and few changing arguments. A toy example could look similar to this code:

```python
list_of_args = [({"a": 1, "b": 2},), ({"a": 2, "b": 4},)]

constant_dict = {"some_object": BigObject, "y": 25, "x": 24}

def my_func(some_object, a,b,x,y):
    # do something with big object

    return result
```

One of these constant arguments is a rather big object that gets read a lot, but not written to. So I thought it would be good to pass this as a shared object. Which lead me to a few questions:

1) How do I pass a shared object as a kwarg? 

As I couldn't find a clear answer to it, I used a wrapper like this:

```python
def my_func_wrapper(constant_dict, args_dict ):
    # just unpack constant and variable args
    return my_func(**constant_dict, **args_dict)
```
Is there a more elegant way to do this without a wrapper?

2) If I pass a shared object as in `constant_dict` as a kwarg, do I also have to pass the object separately for properly sharing witht eh workers?

I imagined it a little bit like this: 

```python

constant_share = (BigObject, {"some_object": BigObject, "y": 25, "x": 24}) # a tuple containing the object and the kwargs referencing the object

def my_func_wrapper(constant_share, args_dict ):
    # just unpack constant_share tuple and pass constant_dict and variable args to function
    BigObject, constant_dict = constant_share
    return my_func(**constant_dict, **args_dict)
```

Am I doing this right or is it not necessary to pass the object seperately as the workers should be forks of the main process anyway?

**Comment by sybrenjansen** [comment]
Hi @sroener ,

1. The short answer is you can't. Shared objects are always passed on as the first argument, no matter what type it is. 

However, in your example you could pass very small objects, like `x` and `y` in your example, by using `functools.partial`:

```
from functools import partial

my_func_ = partial(my_func, x=24, y=25)

with WorkerPool(n_jobs, shared_objects=BigObject) as pool:
    pool.map(my_func_, ...)
```
This will be compatible with your function definition
```
def my_func(some_object, a, b, x, y)
```
As `x` and `y` are integers they provide no overhead in memory. If they are, however, also big objects, then multiprocessing will duplicate them and memory usage will go up.

2. No, you don't need to share it twice. Python always passes on objects by reference. When using shared objects you still do and each worker will access the same object. In other words, your first code example should work as expected, where you're using

```
constant_dict = {"some_object": BigObject, "y": 25, "x": 24}
```

I hope this answers your questions. If not or when you have more questions, just let me know and I'll happily answer them.
