### ISSUE TITLE
Access worker ID from inside worker without passing ID to function

### ISSUE THREAD

**Issue by sroener** [sybrenjansen/mpire#88]
Hi, 

I have a function that gets either supplied to an mpire workerpool or to itertools starmap based on specified CPU cores. Now I would like to write some log messages from inside the worker with the respective worker ID. Is there a way to access the current worker ID from inside the worker/function? 

For example, in the standard multiprocessing library I can do things like this: 

```python
print(f"{multiprocessing.current_process().name},  processing {i} tasks ({i / (endTime - startTime):.1f} per sec) ")
```
Is there something similar in mpire?

**Comment by sybrenjansen** [comment]
Yes there is. Have a look at the docs here: https://sybrenjansen.github.io/mpire/usage/workerpool/worker_id.html

**Comment by sroener** [comment]
I have see this, but from my understanding, I have to pass the ID as first argument to the function. Is there a way without passing the ID as an argument?

**Comment by sybrenjansen** [comment]
You can either use `pass_worker_id=True` and then you don't have to pass the ID yourself, as it is automatically passed to the function as the first argument when the flag is set, similar to when you would use shared objects or worker state. 

Or, as mpire is using multiprocessing primitives under the hood, you can also use `multiprocessing.current_process().name` without issue like in your example.

Option 1:

```
def foo(worker_id, x):
    print(f"{worker_id} received {x}")

with WorkerPool(4, pass_worker_id=True) as pool:
    pool.map(foo, range(100))

# Outputs: 
# 0 received 0
# 1 received 1
# etc.
```

Option 2:
```
def foo(x):
    print(f"{multiprocessing.current_process().name} received {x}")

with WorkerPool(4) as pool:
    pool.map(foo, range(100))

# Outputs:
# Worker-0 received 0
# Worker-1 received 1
# etc.
```

**Comment by sroener** [comment]
Thank you for the detailed answer. The first approach was specifically what I wanted to avoid. I wanted to check if mpire has it's own "copy" of the respective API.

I'll try the second approach and hope everything will work.
