### ISSUE TITLE
Do not vendor `tests` in the wheel published to PyPI

### ISSUE THREAD

**Issue by johnthagen** [sybrenjansen/mpire#89]
When we tried out `mpire` for the first time, our application failed to import. After a fair amount of debugging, we realized that this is because the `tests/` directory is not being properly excluded from the built wheel. It's okay to have your tests in the `sdist` if you like, as sometimes downstream distributors like to have unit tests in the source distribution.

The problem is that we get a `ModuleNotFoundError` when we try to import _our own_ `tests` folder in our local directory (our _own_ unit tests) because it is shadowed by the `tests` package that is installed by the `mpire` wheel.

You can confirm this problem by downloading and unzipping the wheel here:

- https://pypi.org/project/mpire/2.8.0/#files

You will see that there is a `tests` package in the wheel. This is almost certainly not what you to do as it will install this `tests` package into every user's virtual envionment that installs `mpire`.

**Comment by johnthagen** [comment]
You probably want to modify this line:

https://github.com/sybrenjansen/mpire/blob/17d1897e17c272b615f6c39a818ca73c7cc94b92/setup.py#L18

To something like:

- https://stackoverflow.com/a/61274968/

**Comment by sybrenjansen** [comment]
Good point. Thnx for raising the issue and providing a solution as well.

I made a PR to resolve this. I will release it shortly
