### ISSUE TITLE
Dynamically select proper `tqdm` progress bar style

### ISSUE THREAD

**Issue by ma-sadeghi** [sybrenjansen/mpire#95]
Currently, the default `tqdm` style is standard. `tqdm` provides a robust way to select the proper progress bar style consistent with the environment:

```python
from tqdm.auto import tqdm
```

**Comment by sybrenjansen** [comment]
`tqdm.auto` does not always work unfortunately, that's why I stepped away from using it. See #71 and the linked tqmd issue for more information on the matter
