### ISSUE TITLE
Add `rich` as a backend for progress bar

### ISSUE THREAD

**Issue by ma-sadeghi** [sybrenjansen/mpire#96]
It'd be great if `mpire` supported `rich` progress bars. Not that it's not great already, just a nice addition :)

**Comment by sybrenjansen** [comment]
Last I checked `rich` was still an experimental feature of `tqdm`. There's some `tqdm` custom stuff going on under the hood in `mpire` to make everything work and the last time I tried it (a year ago) I gave up, perhaps too quickly. Maybe things have changed in the mean time, I will need to check if I get the time.
